# Site settings. Edit these, plus the files in _data/, to update the site.
title: Nikita Karaev
name: Nikita Karaev
position: Member of Technical Staff
affiliation: Amazon FAR
email: nikkar.nsk@gmail.com
description: >-
  I'm building general-purpose robots at Amazon FAR, following the acquisition of Pixelwise AI, where I was a founder. We're continuing our vision of training robots using internet-scale human data.
  Previously, I was fortunate to do a PhD at [Meta AI](https://ai.facebook.com/) and the [Visual Geometry Group, University of Oxford](https://www.robots.ox.ac.uk/~vgg/), supervised by [Christian Rupprecht](https://chrirupp.github.io), [Natalia Neverova](https://nneverova.github.io), and [Andrea Vedaldi](https://www.robots.ox.ac.uk/~vedaldi/).
  Before my PhD, I completed an engineering program at [École Polytechnique](https://www.polytechnique.edu/en) in beautiful Paris. I also enjoy running and all mountain-related activities 🏔️
# Plain-text summary for search engines and link previews.
tagline: Member of Technical Staff at Amazon FAR working on 3D computer vision and robot learning. Co-author of VGGT, CoTracker, VGGSfM and DynamicStereo.

baseurl: ""
url: "https://nikitakaraevv.github.io"
twitter_username: n_karaev
github_username: nikitakaraevv
google_scholar: DW-X-Y8AAAAJ
google_analytics: G-QN7B6S518N

# Number of news items shown before the "Show more" button.
news_visible: 6

# Build settings
plugins:
  - jekyll-feed

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .bundle/
